name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      application_name:
        description: 'Secret Deployment'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: Configure Cloud Provider Credentials
        run: echo "$GCP_SA_KEY" > key.json && gcloud auth activate-service-account --key-file=key.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Application
        run: |
          cd ${pwd}/cloudsql/
          terraform init
          terraform apply -auto-approve -var-file="terraform.tfvars"
