name: Deploy Secrets

on:
  workflow_dispatch:
    inputs:
      application_name:
        description: 'Type Anything And Press RunWorkflow'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Authenticate to GCP
        run: echo "$GCP_SA_KEY" > key.json && gcloud auth activate-service-account --key-file=key.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          

      - name: Configure Terraform Backend
        run: |
          cd secret/
          terraform init 

      - name: Terraform Apply
        run: |
          cd secret/
          terraform apply -auto-approve -var-file="terraform.tfvars" -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
