name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      application_name:
        description: 'Secret Deployment'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > keyfile.json
          gcloud auth activate-service-account --key-file=keyfile.json
          rm keyfile.json

      - name: Configure Terraform Backend
        run: terraform init 

      - name: Terraform Apply
        run: terraform apply -auto-approve
          terraform apply -auto-approve -var-file="terraform.tfvars"
