name: Deploy to Google Cloud Run with Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Action Yes/No'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [14]
        region: [asia-south1] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.9

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Configure Docker to use the gcloud credential helper
      run: gcloud auth configure-docker -q

    - name: Build and push Docker image to GCR
      run: |
        export IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SECRET_NAME }}
        docker buildx build -t $IMAGE_NAME .
        docker tag $IMAGE_NAME $IMAGE_NAME:$GITHUB_SHA
        echo $IMAGE_NAME
        docker container run -d -p 3000:3000 $IMAGE_NAME:$GITHUB_SHA
        docker push $IMAGE_NAME:$GITHUB_SHA
        docker push $IMAGE_NAME:latest

    - name: Pull Docker Image from GCR
      run: |
        docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SECRET_NAME }}:${{ github.sha }}
          
    - name: Create Environment File
      run: echo "IMAGE_SHA=${{ github.sha }}" >> $GITHUB_ENV

    - name: Apply Terraform Changes
      run: |
       terraform init
       terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="image_tag=${{ github.sha }}" -var="secretname=${{ secrets.SECRET_NAME }}"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GITHUB_SHA: ${{ github.sha }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  SECRET_NAME: ${{ secrets.SECRET_NAME }}
